### ISSUE TITLE
[GERENTE] Consultar os 5 Melhores Clientes

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#10]
1. Deve ser apresentada uma tela contendo somente os seus clientes que possuem os 5 **maiores saldos em conta**
2. Exibir para cada um dos clientes:
- CPF
- Nome
- Cidade
- Estado
- Saldo da conta

3. Deve ser ordenado de forma **decrescente por saldo**;

![Image](https://user-images.githubusercontent.com/61798393/202825387-01371cd4-6c6d-4442-9474-ab5fe4f85f15.png)

**Comment by gjperes** [comment]
Feito, integração json-server ok
