### ISSUE TITLE
[ADMINISTRADOR] Tela Inicial

### ISSUE THREAD

**Issue by Bribudoj** [tdb-turma-balaco-baco/bantads#13]
1. Dashboard contendo todos os gerentes, com os dados:
- CPF;
- Nome;
- E-mail;
- Telefone;

2. Para cada gerente apresenta:
- quantos clientes possui;
-  a totalização (soma) de saldos positivo; 
-  totalização (soma) de saldos negativos.

![Image](https://user-images.githubusercontent.com/61798393/202824847-a107c87f-1816-4388-9716-0748a3d13b5c.png)

**Comment by IzaelJ** [comment]
O grosso já foi feito, só falta a informação de quantos clientes o gerente possui, saldo positivo e negativo. 
Vou reutilizar a lógica de ordenar os nomes por ordem crescente.

**Comment by gjperes** [comment]
ATRASADA A ENTREGA!
