### ISSUE TITLE
[GERENTE] Consultar todos os Clientes

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#14]
1. Deve apresentar em uma tabela todos os **seus Clientes**, contendo os seguintes dados:
- CPF
- Nome
- Cidade
- Estado
- Saldo da conta

2. A tabela deve ser ordenada de forma **Crescente por Nome**
3. Deve ser disponibilizado um campo de texto onde o gerente pode **pesquisar** o cliente por **CPF** (ou parte dele) e **Nome** (ou parte dele)
4. Cada cliente deve possuir um link que, ao ser pressionado, vai para uma tela contendo todos os dados do cliente e de sua conta _(Tela de Detalhe)_

![Image](https://user-images.githubusercontent.com/61798393/202825313-88a929c1-e734-4fe5-9875-ca8ce96a3174.png)

**Comment by gjperes** [comment]
Feito, com json-server

**Comment by gjperes** [comment]
uooooooooooooooooh pipe de busca feitooooooooooooooooooooo

feito
