### ISSUE TITLE
[GERENTE] Tela Inicial do Gerente

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#15]
1. Deve apresentar todos os pedidos de autocadastro para aprovação, como uma tabela, contendo:
- CPF
- Nome
- Salário do cliente

2. Dois botões, para "Aprovar" e "Recusar", em cada um dos pedidos.

![Image](https://user-images.githubusercontent.com/61798393/202825007-6d0d6f6a-c4d8-417e-a323-ca8fbd5dcbdd.png)

**Comment by gjperes** [comment]
Feito e com service pronta, integrada com json-server
