### ISSUE TITLE
[ADMINISTRADOR] Remoção de Gerente (D)

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#17]
Origem: Botão de ação EDITAR na tabela (Tela [ADMINISTRADOR] Listagem de Gerentes (R) )

1. Ao ser removido um gerente:
- As contas que ele mantém devem ser atribuídas para o gerente que possua menos contas atreladas naquele momento;
- Não permitir a remoção do último gerente do banco.
2. Apresenta mensagem solicitando confirmação da ação (Excluir ? Sim : Não)

![Image](https://user-images.githubusercontent.com/61798393/202827603-4325d3f0-6b41-4ca2-94af-d818f1aadbca.png)

**Comment by gjperes** [comment]
ATRASADA A ENTREGA!
