### ISSUE TITLE
[ADMINISTRADOR] Tela Relatório de Clientes

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#18]
1. Deve listar um relatório de todos os clientes, com:
- Nome do cliente;
- CPF do cliente;
- Limite do cliente;
- Nome do gerente; 
- Saldo do cliente; 

2. Deve-se ordenar de forma crescente por nome do cliente.

![Image](https://user-images.githubusercontent.com/61798393/202825007-6d0d6f6a-c4d8-417e-a323-ca8fbd5dcbdd.png)

**Comment by gjperes** [comment]
A princípio pronto, resolvido no PR #33
