### ISSUE TITLE
[ADMINISTRADOR] Alteração de Gerente (U)

### ISSUE THREAD

**Issue by Mateus-Wosniaki** [tdb-turma-balaco-baco/bantads#20]
Origem: Botão de ação EDITAR na tabela (Tela [ADMINISTRADOR] Listagem de Gerentes (R) )
**DEPENDÊNCIA**: TELA [ADMINISTRADOR] Inserção de Gerente

1. Pode-se alterar todos os dados, menos seu CPF.

![Image](https://user-images.githubusercontent.com/61798393/202823514-7efb2cdf-c9eb-4fca-b762-0c2d9121690d.png)

**Comment by gjperes** [comment]
ATRASADA A ENTREGA!
