### ISSUE TITLE
[CLIENTE] Tela Inicial

### ISSUE THREAD

**Issue by gjperes** [tdb-turma-balaco-baco/bantads#5]
## Tela

Deve contar as ações que o cliente pode realizar:

- Depositar
- Sacar
- Tranferir

Deve exibir o campo SALDO

`RN: Caso o saldo seja negativo deve exibir em VERMELHO e com SINAL de "-"`

---------

![Image](https://user-images.githubusercontent.com/61798393/202823488-b5769504-a236-471d-9354-b59a555eb526.png)

---------

### Card de Saldo

Informações do saldo para o cliente:
- Saldo Atual
- Limite
- Nome do Gerente

![Image](https://user-images.githubusercontent.com/61798393/202823606-be9b5603-8701-49be-9120-b289d663a433.png)

### Cards de Depósito, Saque e Transferência

Componente de Card contendo o título da ação + botão para acessar a tela da operação

![Image](https://user-images.githubusercontent.com/61798393/202824196-e5c50f4a-b330-4947-99ab-ecc26954e994.png)

**Comment by gjperes** [comment]
Bloqueio: preciso da implementação de autenticação, acho que ela deve ser prioridade máxima, inclusive @Mateus-Wosniaki @Bribudoj @IzaelJ

**Comment by Mateus-Wosniaki** [comment]
Contras da autenticação agora:

100% de chance de retrabalho futuro;
50% das telas não estão prontas ou estão em branches separadas.

Preciso entender o pq da autenticação agora.
